version: '3.5'

services:
  mongodb:
    #image: mongodb/mongodb-community-server:6.0-ubi8
    image: mongo:latest
    deploy:
      mode: global
      resources:
        limits:
          memory: 4096M
    volumes:
      - mongodb:/data/db
   #ports:
     # - 27017:27017
    networks:
      - database
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    image: mongo-express:latest
    ports:
      - 8082:8081
    networks:
      - database
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongodb:27017/

volumes:
  mongodb: {}
  
networks:
  database:
    external: true
    name: database
