version: '3.5'

services:
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/run/docker.sock:/var/run/docker.sock:rw
    networks:
      - private
    ports:
      - 8080
    deploy:
      mode: global
      resources:
        limits:
          memory: 128M

  node-exporter:
    image: prom/node-exporter
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    ports:
      - 9100
    environment:
      - HOST_HOSTNAME=/etc/host_hostname
    networks:
      - private
    deploy:
      mode: global
      resources:
        limits:
          memory: 128M

  blackbox-exporter:
    image: prom/blackbox-exporter:v0.12.0
    networks:
      - private
    deploy:
      mode: replicated
      replicas: 1
      resources:
        limits:
          memory: 128M

  alertmanager:
    image: prom/alertmanager
    configs:
      - source: alertmanager_config
        target: /etc/alertmanager/config.yml
    command:
      - '--config.file=/etc/alertmanager/config.yml'
      - '--storage.path=/alertmanager'
    volumes:
      - alertmanager:/alertmanager
    networks:
      - private
    ports:
      - 9093
    deploy:
      replicas: 1
      placement:
        constraints:
           - node.role==manager
      resources:
        limits:
          memory: 128M

  prometheus:
    image: prom/prometheus
    user: root
    volumes:
      - promconfig:/etc/prometheus
      - promdata:/prometheus
    configs:
      - source: prometheus_config
        target: /etc/prometheus/prometheus.yml
      - source: prometheus_rules
        target: /etc/prometheus/alert.rules
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
    networks:
      - private
    ports:
      - 9090
    deploy:
      placement:
        constraints:
          - node.role==manager
      resources:
        limits:
          memory: 512M

  grafana:
    image: grafana/grafana
    volumes:
      - grafanadata:/var/lib/grafana
      - grafana_provisioning:/etc/grafana/provisioning
    configs:
      - source: grafana_config_datasource
        target: /etc/grafana/provisioning/datasources/prometheus.yml
    environment:
      - GF_SERVER_ROOT_URL=http://localhost:3002
      - GF_SECURITY_ADMIN_USER=${GRAFANA_USER:-admin}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD:-admin}
      - GF_USERS_ALLOW_SIGN_UP=false
      - PROMETHEUS_ENDPOINT=http://prometheus:9090
    networks:
      - private
    ports:
      - 3002:3000
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role==manager
      resources:
        limits:
          memory: 512M

networks:
  private:
    name: private
    driver: overlay

volumes:
  promconfig: {}
  promdata: {}
  grafanadata: {}
  alertmanager: {}
  grafana_provisioning: {}

configs:
  alertmanager_config:
    file: ./alertmanager/configs/alertmanager.yml
  prometheus_config:
    file: ./prometheus/configs/prometheus.yml
  prometheus_rules:
    file: ./prometheus/rules/alert.rules
  grafana_config_datasource:
    file: ./grafana/provisioning/datasources/prometheus.yml
