version: '3.7'

services:
  oktoplace-shop:
    image: oktoplace/oktoplace-shop:latest
    deploy:
      mode: replicated
      replicas: 4
      resources:
        limits:
          memory: 1024M
    ports:
      - 8081:8081
    networks:
      - database

  oktoplace:
    image: oktoplace/oktoplace:latest
    ports:
      - 3001:3001
    deploy:
      mode: global
      resources:
        replicas: 4
      resources:
        limits:
          memory: 1024M

networks:
  database:
    external: true
    name: database
