version: '3.5'

services:
  solr:
    image: solr:latest
    networks:
      - database
      - host
    ports:
      - 8983:8983
    deploy:
      mode: global
      resources:
        limits:
          memory: 1024M
          
networks:
  database:
    external: true
    name: database
  host:
    external: true
    name: host
